<-- A mock GCIDE dictionary for GNU Dico test suite.  File 4 of 26.

    GNU Dico is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3, or (at your option)
    any later version.

    GNU Dico is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with GNU Dico.  If not, see <http://www.gnu.org/licenses/>. -->

<p><centered><point26>D.</point26></centered></p>

<p><hw>database</hw> <pos>n.</pos> <def>An organized body of related information</def><br/
[<source>Dico testsuite</source>]</p>

<p><q>Has everyone noticed that all the letters of the word \'bddatabase\'b8 are
typed with the left hand?  Now the layout of the <er>QWERTY</er> typewriter
keyboard was designed, among other things, to facilitate the even use
of both hands.  It follows, therefore, that writing about databases is
not only unnatural, but a lot harder than it appears.</q> <rj><qau>The Fortune program.</qau></rj><br/</p><br/
[<source>Dico testsuite</source>]</p>

<p><hw>Dou"ble</hw> <pr>(d<ucr/b"'l)</pr>, <pos>a.</pos> <def>A floating-point data type.  See <er>Float</er>.</def><br/
[<source>Dico testsuite</source>]</p>

<-- Local variables: -->
<-- mode: sgml -->
<-- End: -->
