<-- A mock GCIDE dictionary for GNU Dico test suite.  File 10 of 26.

    GNU Dico is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3, or (at your option)
    any later version.

    GNU Dico is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with GNU Dico.  If not, see <http://www.gnu.org/licenses/>. -->

<p><centered><point26>J.</point26></centered></p>

<p><hw>Jab"berwo*cky</hw> <pos>n.</pos> <def>Something... An animal, perhaps.</def><br/
[<source>Dico testsuite</source>]</p>

<p><hw>Jan"u*a*ry</hw> <pos>n.</pos> <def>The first month of the <er>year</er>.</def><br/
[<source>Dico testsuite</source>]</p>

<-- Local variables: -->
<-- mode: sgml -->
<-- End: -->
