<-- A mock GCIDE dictionary for GNU Dico test suite.  File 5 of 26.

    GNU Dico is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3, or (at your option)
    any later version.

    GNU Dico is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with GNU Dico.  If not, see <http://www.gnu.org/licenses/>. -->

<p><centered><point26>E.</point26></centered></p>

<p><hw>Ed</hw> <pos>n.</pos> <def>An editor.</def><br/
[<source>Dico testsuite</source>]</p>

<p><hw>Emacs</hw> <pos>n.</pos> <def>An editor too.</def><br/
[<source>Dico testsuite</source>]</p>

<p><hw>Ed"it</hw> <pos>v. t.</pos> <def>Kind of exhausting work.</def><br/
[<source>Dico testsuite</source>]</p>

<p><hw>E*nu"mer*a*tion</hw> <pos>n.</pos> <def>A data type.</def>
[<source>Dico testsuite</source>]</p>

<-- Local variables: -->
<-- mode: sgml -->
<-- End: -->
