<-- A mock GCIDE dictionary for GNU Dico test suite.  File 8 of 26.

    GNU Dico is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3, or (at your option)
    any later version.

    GNU Dico is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with GNU Dico.  If not, see <http://www.gnu.org/licenses/>. -->

<p><centered><point26>H.</point26></centered></p>

<p><hw>Help</hw> <pos>n.</pos> <def>A thing greatly needed when writing this stuff.</def><br/
[<source>Dico testsuite</source>]</p>

<p><hw>Hack</hw> <pos>v.</pos> <def>To work on a program.</def><br/
[<source>Dico testsuite</source>]</p>


<-- Local variables: -->
<-- mode: sgml -->
<-- End: -->
