<-- A mock GCIDE dictionary for GNU Dico test suite.  File 7 of 26.

    GNU Dico is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3, or (at your option)
    any later version.

    GNU Dico is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with GNU Dico.  If not, see <http://www.gnu.org/licenses/>. -->

<p><centered><point26>G.</point26></centered></p>

<p><hw>GNU</hw> <pos>n.</pos> <def>GNU's Not UNIX.<def><br/
[<source>Dico testsuite</source>]</p>

<p><hw>Gram"mar</hw> <pos>n.</pos> <def>A branch of linguistics.</def><br/
[<source>Dico testsuite</source>]</p>

<p><hw>Gy`ro*scop"ic</hw> <pos>a.</pos> <def>Going in circles.</def><br/
[<source>Dico testsuite</source>]</p>

<-- Local variables: -->
<-- mode: sgml -->
<-- End: -->
